name: Ruby

on:
  push:
    branches:
      - main

jobs:
    ruby-action:
      name: Test Ruby Action
      runs-on: ubuntu-latest
      steps:
        - name: Set up Ruby
          uses: ruby/setup-ruby@v1.139.0
          with:
            ruby-version: 2.6.8
            rubygems: 'latest'
            bundler: 2.3.3
            bundler-cache: true
            cache-version: 1


        - name: Set Up Ruby alternative
          uses: ruby/setup-ruby@v1.139.0
          with:
            ruby-version: 2.6.8
            bundler: 2.3.3
            bundler-cache: true
            cache-version: 1

        - name: Update RubyGems
          run: gem update --system
