name: Ruby Versions

on:
  push:
    branches:
      - main

jobs:
  ruby-action:
    name: Ruby Versions
    runs-on: ubuntu-latest
    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.138.0
        with:
          ruby-version: 2.6.8
          bundler: 2.3.3

      - name: Print Ruby version
        run: ruby --version

      - name: Print Gem version
        run: gem --version

      - name: Print Bundler version
        run: bundler --version


#      - name: Set up Ruby
#        uses: ruby/setup-ruby@v1.138.0
#        with:
#          ruby-version: 2.6.8
##          working-directory: backend
#
#      - name: Print Ruby version before
#        run: ruby --version
#
#      - name: Print Gem version before
#        run: gem --version
#
#      - name: Print Bundler version before
#        run: bundler --version
#
#
#      - name: Set up Bundler
#        run: |
#          gem update --system
#          gem install bundler -v 2.3.3
#
#
#      - name: Print Ruby version
#        run: ruby --version
#
#      - name: Print Gem version
#        run: gem --version
#
#      - name: Print Bundler version
#        run: bundler --version